version: "{build}"

image: Visual Studio 2019

skip_tags: true
clone_depth: 1

build_script:
  - ps: .\Publish.ps1

test:
  assemblies:
    only:
      - **/JiraTimers.Tests.dll

artifacts:
  - path: '**\*.nupkg'
  - path: '**\JiraTimers.Setup.*.msi'