version: "{build}"

image: Visual Studio 2022

skip_tags: true
clone_depth: 1

build_script:
  - ps: .\Publish.ps1

after_build:
  - ps: dotnet test src/JiraTimers.Tests/JiraTimers.Tests.csproj

artifacts:
  - path: '**\*.nupkg'
  - path: '**\JiraTimers.Setup.*.msi'
  - path: "JiraTimers*.zip"
