name: Build Package

on: push

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install DotNet
        uses: actions/setup-dotnet@v1

      - name: Create Source Packages
        shell: pwsh
        run: ./Publish.ps1

      - name: Create Nuget package artifact
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: "**\\*.nupkg"

      - name: Create MSI installer artifact
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: "**\\JiraTimers.Setup.*.msi"

      - name: Create archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: "JiraTimers*.zip"
